version: '3.3'
services:
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v5.5.0
    ports:
      - 8090:8080
    volumes:
      - ./tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
      - ./policies:/opt/tyk-gateway/policies
    environment:
      - TYK_GW_SECRET=foo
      - TYK_LOGLEVEL=debug
      - TYK_GW_HTTPSERVEROPTIONS_SSLINSECURESKIPVERIFY=false
    depends_on:
      - tyk-redis

  tyk-redis:
    image: redis:6.2.7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - "8100:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    command: start-dev

  postgres:
    image: postgres:16.6-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi-app:
    image: fastapi-demo
    ports:
      - 8000:8000

volumes:
  postgres_data:
  redis_data:


